In [1]:
import numpy as np
import pandas as pd

Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days


In [2]:
df_wine = pd.read_csv('data/wine.csv')

In [3]:
df_wine.describe()

Year      Price  WinterRain       AGST  HarvestRain        Age  \
count    25.000000  25.000000   25.000000  25.000000    25.000000  25.000000   
mean   1965.800000   7.067224  605.280000  16.509336   148.560000  17.200000   
std       7.691987   0.650341  132.277965   0.675397    74.419464   7.691987   
min    1952.000000   6.204900  376.000000  14.983300    38.000000   5.000000   
25%    1960.000000   6.518800  536.000000  16.200000    89.000000  11.000000   
50%    1966.000000   7.121100  600.000000  16.533300   130.000000  17.000000   
75%    1972.000000   7.495000  697.000000  17.066700   187.000000  23.000000   
max    1978.000000   8.493700  830.000000  17.650000   292.000000  31.000000   

          FrancePop  
count     25.000000  
mean   49694.436760  
std     3665.270243  
min    43183.569000  
25%    46583.995000  
50%    50254.966000  
75%    52894.183000  
max    54602.193000

In [4]:
from sklearn.linear_model import LinearRegression

In [14]:
model = LinearRegression()
model.fit(df_wine['AGST'].reshape(-1,1), df_wine['Price'].reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
df_wine['Price'].reshape(-1,1)

array([[ 7.495 ],
       [ 8.0393],
       [ 7.6858],
       [ 6.9845],
       [ 6.7772],
       [ 8.0757],
       [ 6.5188],
       [ 8.4937],
       [ 7.388 ],
       [ 6.7127],
       [ 7.3094],
       [ 6.2518],
       [ 7.7443],
       [ 6.8398],
       [ 6.2435],
       [ 6.3459],
       [ 7.5883],
       [ 7.1934],
       [ 6.2049],
       [ 6.6367],
       [ 6.2941],
       [ 7.292 ],
       [ 7.1211],
       [ 6.2587],
       [ 7.186 ]])

In [23]:
np.shape(df_wine['Price'].values)

(25,)

In [24]:
np.shape(df_wine['Price'])

(25,)

In [25]:
np.shape(df_wine['Price'].reshape(-1,1))

(25, 1)

In [26]:
model.predict(15)

array([[ 6.1086533]])

In [27]:
model.predict(30)

array([[ 15.63506791]])

In [33]:
model.coef_

array([[ 0.63509431]])

In [34]:
model.intercept_

array([-3.41776131])

In [37]:
model.residues_

/Users/fuyangliu/anaconda/lib/python2.7/site-packages/sklearn/utils/__init__.py:93: DeprecationWarning: Function residues_ is deprecated; ``residues_`` is deprecated and will be removed in 0.19
  warnings.warn(msg, category=DeprecationWarning)


array([ 5.73487515])

In [43]:
# To get the R^2 score:

model.score(df_wine['AGST'].reshape(-1,1),  df_wine['Price'].reshape(-1,1))

0.43502316779991984

In [46]:
model2 = LinearRegression()
model2.fit(df_wine[['AGST', 'HarvestRain']], df_wine[['Price']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [50]:
# To get the R^2 score:

model2.score(df_wine[['AGST', 'HarvestRain']],  df_wine[['Price']])

0.70737076620494155

In [51]:
model3 = LinearRegression()
model3.fit(df_wine[['AGST', 'HarvestRain', 'WinterRain', 'Age', 'FrancePop']], df_wine[['Price']])
model3.score(df_wine[['AGST', 'HarvestRain', 'WinterRain', 'Age', 'FrancePop']],  df_wine[['Price']])

0.82935922232990356

In [59]:
# SSE
(model3.predict(df_wine[['AGST', 'HarvestRain', 'WinterRain', 'Age', 'FrancePop']])
  - df_wine[['Price']]).apply(lambda x: x**2).apply(np.sum)

Price    1.732113
dtype: float64

## Correlation in Python

In [60]:
from pydoc import help
from scipy.stats.stats import pearsonr
help(pearsonr)


Help on function pearsonr in module scipy.stats.stats:

pearsonr(x, y)
    Calculates a Pearson correlation coefficient and the p-value for testing
    non-correlation.
    
    The Pearson correlation coefficient measures the linear relationship
    between two datasets. Strictly speaking, Pearson's correlation requires
    that each dataset be normally distributed. Like other correlation
    coefficients, this one varies between -1 and +1 with 0 implying no
    correlation. Correlations of -1 or +1 imply an exact linear
    relationship. Positive correlations imply that as x increases, so does
    y. Negative correlations imply that as x increases, y decreases.
    
    The p-value roughly indicates the probability of an uncorrelated system
    producing datasets that have a Pearson correlation at least as extreme
    as the one computed from these datasets. The p-values are not entirely
    reliable but are probably reasonable for datasets larger than 500 or so.
    
    Parameters


In [62]:
pearsonr(df_wine[['WinterRain']], df_wine[['Price']])

(array([ 0.13665055]), array([ 0.51482762]))

In [67]:
pearsonr(df_wine[['WinterRain']], df_wine[['Price']])

(array([ 0.13665055]), array([ 0.51482762]))